### ISSUE TITLE
Failed to turn code into token

### ISSUE THREAD

**Issue by bibinvrgs** [apiman/apiman-docker#27]
apiman/on-wildfly11 on docker returns below error while login to  apimanui

```
ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-4) failed to turn code into token: java.net.NoRouteToHostException: No route to host (Host unreachable)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
```

**Comment by EricWittmann** [comment]
This is usually related to network routing with docker.  The failure is when the Keycloak auth adapter is trying to make an HTTP call to the Keycloak server in order to turn an auth code into an auth token.  The adapter is code running on the server (in Wildfly) that is trying to make the HTTP call - so the Wildfly application needs to be able to make that call.  Whatever it's trying is clearly failing, but I can't tell from the info you included what it's trying.

**Comment by volkflo** [comment]
I think this question is answered. If not feel free to open an issue again :)
