### ISSUE TITLE
apiman-gateway not connecting to default data source with apiman/on-wildfly:latest

### ISSUE THREAD

**Issue by jesseerdmann** [apiman/apiman-docker#30]
I updated to a the latest docker image today, got rid of my relevant volumes and started a clean container after having been away from setting up a local docker instance for a few weeks.  The hash I have for the image is 789ce218b716. 

I have set up a simple echo service and created a client for it within APIMan. When I copy the API endpoint for the client with the API Key as a request parameter I am getting a 502 response from the gateway with the message "Unable to connect to backend".  I'll post the stack later, but as far as I can tell the default configuration is to use a database file in /opt/jboss/wildfly/standalone/data/h2.  The files appear to be present with the same permissions as the apiman-manager-api database files. Any suggestions where to look or what to configure to fix this?

Here is the contents of /opt/jboss/wildfly/standalone/deployments/apiman-gateway-ds.xml

> [jboss@api deployments]$ cat apiman-gateway-ds.xml 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<datasources>
<datasource jndi-name="java:jboss/datasources/apiman-gateway" pool-name="apiman-gateway" enabled="true"
   use-java-context="true">
   <connection-url>jdbc:h2:${jboss.server.data.dir}${/}h2${/}apiman-gateway;MVCC=true</connection-url>
   <driver>h2</driver>
   <security>
     <user-name>sa</user-name>
   </security>
 </datasource>
</datasources>
```

From the server log I see `standalone/log/server.log:50:	jboss.server.data.dir = /opt/jboss/wildfly/standalone/data`

Here is the listing of /opt/jboss/wildfly/standalone/data/h2:

> [jboss@api h2]$ ls -la
> total 2136
> drwxr-xr-x 2 jboss jboss    4096 Dec  4 20:46 .
> drwxr-xr-x 9 jboss jboss    4096 Dec  4 20:27 ..
> -rw-r--r-- 1 jboss jboss   36864 Dec  4 20:39 apiman-gateway.mv.db
> -rw-r--r-- 1 jboss jboss     145 Dec  4 20:27 apiman-gateway.trace.db
> -rw-r--r-- 1 jboss jboss  143360 Dec  4 20:33 apiman-manager-api.mv.db
> -rw-r--r-- 1 jboss jboss     139 Dec  4 20:27 apiman-manager-api.trace.db
> -rw-r--r-- 1 jboss jboss     136 Dec  4 20:27 keycloak.lock.db
> -rwxr-xr-x 1 jboss jboss 1986560 Dec  4 20:30 keycloak.mv.db

And here is the reported stack trace from the HTTP request.

```
io.apiman.gateway.engine.beans.exceptions.ConnectorException: Unable to connect to backend
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.handler.ErrorHandler.handleConnectionError(ErrorHandler.java:30)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.handleConnectionError(HttpApiConnection.java:407)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.connect(HttpApiConnection.java:209)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.<init>(HttpApiConnection.java:120)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.HttpConnectorFactory$1.connect(HttpConnectorFactory.java:119)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$4(ApiRequestExecutorImpl.java:284)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:238)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:152)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.RateLimitingPolicy$1.handle(RateLimitingPolicy.java:104)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.RateLimitingPolicy$1.handle(RateLimitingPolicy.java:91)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.InMemoryRateLimiterComponent.accept(InMemoryRateLimiterComponent.java:69)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.RateLimitingPolicy.doApply(RateLimitingPolicy.java:91)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.RateLimitingPolicy.doApply(RateLimitingPolicy.java:45)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.AbstractMappedPolicy.apply(AbstractMappedPolicy.java:73)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.RequestChain.lambda$applyPolicy$0(RequestChain.java:67)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.executeInPolicyContextLoader(Chain.java:299)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.RequestChain.applyPolicy(RequestChain.java:66)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.RateLimitingPolicy$1.handle(RateLimitingPolicy.java:104)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.RateLimitingPolicy$1.handle(RateLimitingPolicy.java:91)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.InMemoryRateLimiterComponent.accept(InMemoryRateLimiterComponent.java:69)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.RateLimitingPolicy.doApply(RateLimitingPolicy.java:91)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.RateLimitingPolicy.doApply(RateLimitingPolicy.java:45)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policies.AbstractMappedPolicy.apply(AbstractMappedPolicy.java:73)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.RequestChain.lambda$applyPolicy$0(RequestChain.java:67)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.executeInPolicyContextLoader(Chain.java:299)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.RequestChain.applyPolicy(RequestChain.java:66)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$5(ApiRequestExecutorImpl.java:300)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$loadPolicies$7(ApiRequestExecutorImpl.java:681)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.PolicyFactoryImpl.doLoadFromClasspath(PolicyFactoryImpl.java:143)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.policy.PolicyFactoryImpl.loadPolicy(PolicyFactoryImpl.java:102)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:649)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$6(ApiRequestExecutorImpl.java:412)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:189)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.SecureRegistryWrapper$2.handle(SecureRegistryWrapper.java:171)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.jdbc.CachingJdbcRegistry.getContract(CachingJdbcRegistry.java:102)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.SecureRegistryWrapper.getContract(SecureRegistryWrapper.java:171)
    at deployment.apiman-gateway.war//io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:378)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:178)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.GatewayServlet.service(GatewayServlet.java:79)
    at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
    at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
    at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
    at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
    at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
    at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
    at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
    at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
    at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
    at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
    at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
    at io.undertow.core@2.1.3.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
    at io.undertow.core@2.1.3.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
    at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
    at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
    at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at deployment.apiman-gateway.war//com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:100)
    at deployment.apiman-gateway.war//com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
    at deployment.apiman-gateway.war//com.squareup.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
    at deployment.apiman-gateway.war//com.squareup.okhttp.Connection.connect(Connection.java:143)
    at deployment.apiman-gateway.war//com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
    at deployment.apiman-gateway.war//com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
    at deployment.apiman-gateway.war//com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
    at deployment.apiman-gateway.war//com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
    at deployment.apiman-gateway.war//com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.ok.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:435)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.ok.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:116)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.ok.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:91)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.ok.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:27)
    at deployment.apiman-gateway.war//io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.connect(HttpApiConnection.java:206)
    ... 81 more

```

**Comment by EricWittmann** [comment]
The `Unable to connect to backend` error indicates that the Gateway was unable to connect to your echo service.  From the stack it looks like it tried to open a standard TCP socket but the connection was refused.  Possibly the echo service isn't running?  Or maybe it's not accessible by the Gateway due to docker networking?

**Comment by volkflo** [comment]
Maybe you could tell us the API Implementation Endpoint of your Echo-API server. 
E.g. "localhost" will not work in docker environments.

**Comment by jesseerdmann** [comment]
Oh geeze. Sorry for the misinterpretation.Thanks for setting me straight!

**Comment by EricWittmann** [comment]
No problemo.
