### ISSUE TITLE
docker-compose'd install fails to restart/up again after making changes

### ISSUE THREAD

**Issue by k1th** [apiman/apiman-docker#31]
Dockerfile:

```
FROM apiman/on-wildfly
RUN $JBOSS_HOME/bin/add-user.sh admin admin123! --silent
EXPOSE 8787
ENTRYPOINT ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "-c", "standalone-apiman.xml", "--debug"]
```

Compose file:
```
version: "3"
services:
  apiman:
    build: apiman
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990

  echo-server:
    image: ealen/echo-server:latest
```

After starting successfully and 
- setting up Keycloak with 
  - new realm
  - client
  - users
  - roles
- creating an API with the Keycloak Plugin (after installing it in the GUI)
- deploying apiman-quickstarts-echo-service-1.3.1.Final.war into Wildfly
- successfully testing the setup

we stopped the running containers and did a `docker-compose up` again.

This ALWAYS results in the following exception/death/unusable compose setup. We were able to reproduce this every time and it seems to start happening after adding and configuring the Keycloak Plugin and hitting the API using it.
```
apiman_1       | 16:49:46,572 INFO  [org.hibernate.hql.internal.QueryTranslatorFactoryInitiator] (ServerService Thread Pool -- 92) HHH000397: Using ASTQueryTranslatorFactory
apiman_1       | 16:49:46,768 INFO  [stdout] (Thread-121) Import not needed.
apiman_1       | 16:49:46,780 INFO  [stdout] (Thread-121) ----------------------------
apiman_1       | 16:49:46,781 INFO  [stdout] (Thread-121) Starting apiman data import.
apiman_1       | 16:49:46,784 INFO  [stdout] (Thread-121) Import not needed.
apiman_1       | 16:49:46,785 INFO  [stdout] (Thread-121) ----------------------------
apiman_1       | 16:49:46,786 INFO  [stdout] (Thread-121) Starting apiman data import.
apiman_1       | 16:49:46,795 INFO  [stdout] (Thread-121) Import not needed.
apiman_1       | 16:49:47,690 WARN  [org.jboss.modules.define] (ServerService Thread Pool -- 92) Failed to define class org.keycloak.models.sessions.infinispan.initializer.SessionInitializerWorker in Module "org.keycloak.keycloak-model-infinispan" version 10.0.2 from local module loader @ebaa6cb (finder: local module finder @906d29b (roots: /opt/jboss/wildfly/modules,/opt/jboss/wildfly/modules/system/layers/keycloak,/opt/jboss/wildfly/modules/system/layers/base,/opt/jboss/wildfly/modules/system/add-ons/keycloak)): java.lang.NoClassDefFoundError: Failed to link org/keycloak/models/sessions/infinispan/initializer/SessionInitializerWorker (Module "org.keycloak.keycloak-model-infinispan" version 10.0.2 from local module loader @ebaa6cb (finder: local module finder @906d29b (roots: /opt/jboss/wildfly/modules,/opt/jboss/wildfly/modules/system/layers/keycloak,/opt/jboss/wildfly/modules/system/layers/base,/opt/jboss/wildfly/modules/system/add-ons/keycloak))): org/infinispan/distexec/DistributedCallable
apiman_1       | 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
apiman_1       | 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
apiman_1       | 	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
apiman_1       | 	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
apiman_1       | 	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
apiman_1       | 	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
apiman_1       | 	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
apiman_1       | 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
apiman_1       | 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
apiman_1       | 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
apiman_1       | 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
apiman_1       | 	at org.keycloak.keycloak-model-infinispan@10.0.2//org.keycloak.models.sessions.infinispan.initializer.InfinispanCacheInitializer.startLoadingImpl(InfinispanCacheInitializer.java:150)
apiman_1       | 	at org.keycloak.keycloak-model-infinispan@10.0.2//org.keycloak.models.sessions.infinispan.initializer.InfinispanCacheInitializer.startLoading(InfinispanCacheInitializer.java:108)
apiman_1       | 	at org.keycloak.keycloak-model-infinispan@10.0.2//org.keycloak.models.sessions.infinispan.initializer.DBLockBasedCacheInitializer.startLoading(DBLockBasedCacheInitializer.java:75)
apiman_1       | 	at org.keycloak.keycloak-model-infinispan@10.0.2//org.keycloak.models.sessions.infinispan.initializer.CacheInitializer.loadSessions(CacheInitializer.java:41)
apiman_1       | 	at org.keycloak.keycloak-model-infinispan@10.0.2//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$2.run(InfinispanUserSessionProviderFactory.java:186)
apiman_1       | 	at org.keycloak.keycloak-server-spi-private@10.0.2//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:227)
apiman_1       | 	at org.keycloak.keycloak-model-infinispan@10.0.2//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory.loadPersistentSessions(InfinispanUserSessionProviderFactory.java:172)
apiman_1       | 	at org.keycloak.keycloak-model-infinispan@10.0.2//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$1.lambda$onEvent$0(InfinispanUserSessionProviderFactory.java:126)
apiman_1       | 	at org.keycloak.keycloak-server-spi-private@10.0.2//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:227)
apiman_1       | 	at org.keycloak.keycloak-server-spi-private@10.0.2//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithTimeout(KeycloakModelUtils.java:267)
apiman_1       | 	at org.keycloak.keycloak-model-infinispan@10.0.2//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$1.onEvent(InfinispanUserSessionProviderFactory.java:122)
apiman_1       | 	at org.keycloak.keycloak-services@10.0.2//org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:72)
apiman_1       | 	at org.keycloak.keycloak-services@10.0.2//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:170)
apiman_1       | 	at org.keycloak.keycloak-wildfly-extensions@10.0.2//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:29)
apiman_1       | 	at org.keycloak.keycloak-services@10.0.2//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:125)
apiman_1       | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
apiman_1       | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
apiman_1       | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
apiman_1       | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
apiman_1       | 	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)
apiman_1       | 	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2811)
apiman_1       | 	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:371)
apiman_1       | 	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:283)
apiman_1       | 	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:93)
apiman_1       | 	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:140)
apiman_1       | 	at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
apiman_1       | 	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
apiman_1       | 	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
apiman_1       | 	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
apiman_1       | 	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)
apiman_1       | 	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
apiman_1       | 	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:585)
apiman_1       | 	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556)
apiman_1       | 	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
apiman_1       | 	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
apiman_1       | 	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
apiman_1       | 	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
apiman_1       | 	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
apiman_1       | 	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
apiman_1       | 	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
apiman_1       | 	at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598)
apiman_1       | 	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
apiman_1       | 	at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
apiman_1       | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
apiman_1       | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
apiman_1       | 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
apiman_1       | 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
apiman_1       | 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
apiman_1       | 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
apiman_1       | 	at java.base/java.lang.Thread.run(Thread.java:834)
apiman_1       | 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)
apiman_1       |
apiman_1       | 16:49:47,701 FATAL [org.keycloak.services] (ServerService Thread Pool -- 92) java.lang.NoClassDefFoundError: Failed to link org/keycloak/models/sessions/infinispan/initializer/SessionInitializerWorker (Module "org.keycloak.keycloak-model-infinispan" version 10.0.2 from local module loader @ebaa6cb (finder: local module finder @906d29b (roots: /opt/jboss/wildfly/modules,/opt/jboss/wildfly/modules/system/layers/keycloak,/opt/jboss/wildfly/modules/system/layers/base,/opt/jboss/wildfly/modules/system/add-ons/keycloak))): org/infinispan/distexec/DistributedCallable
```

**Comment by EricWittmann** [comment]
I have no idea what could cause that, @stianst any ideas on this?

**Comment by k1th** [comment]
This is very reproducible. Had it 5 times. After that I finished testing because I did not want to enter my test data yet another time :)

**Comment by volkflo** [comment]
I am a little bit confused as well, but we could try to update keycloak to the latest version. We are now on 10.X. Maybe this is fixed already :)

**Comment by EricWittmann** [comment]
Worth a shot - I think 12.0.1 is just recently out.

**Comment by k1th** [comment]
I rebuilt apiman apiman-distro-wildfly-2.0.1-SNAPSHOT-overlay.zip with 
`    <version.org.keycloak>12.0.1</version.org.keycloak>`, 
created a new docker docker image using that overlay zip and it seems to work now.

**Comment by volkflo** [comment]
@k1th This sounds good, can you provide a PR with your changes please? :)

**Comment by k1th** [comment]
yeah, I can do that. Some tests fail though:

```
-------------------------------------------------------------------------------
Test set: io.apiman.manager.test.es.EsMetricsAccessorTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.866 sec <<< FAILURE! - in io.apiman.manager.test.es.EsMetricsAccessorTest
io.apiman.manager.test.es.EsMetricsAccessorTest  Time elapsed: 1.866 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:287)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:129)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595)
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:91)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:155)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.listImagesCmd(LazyDockerClient.java:12)
	at org.testcontainers.images.LocalImagesCache.maybeInitCache(LocalImagesCache.java:68)
	at org.testcontainers.images.LocalImagesCache.get(LocalImagesCache.java:32)
	at org.testcontainers.images.AbstractImagePullPolicy.shouldPull(AbstractImagePullPolicy.java:18)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:59)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:26)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1266)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:603)
	at org.testcontainers.elasticsearch.ElasticsearchContainer.<init>(ElasticsearchContainer.java:49)
	at io.apiman.manager.test.es.EsMetricsAccessorTest.<clinit>(EsMetricsAccessorTest.java:57)

io.apiman.manager.test.es.EsMetricsAccessorTest  Time elapsed: 1.866 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.apiman.manager.test.es.EsMetricsAccessorTest
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by volkflo** [comment]
I think this is not related to keycloak. More a problem with the elasticserach test tool.
If you provide a PR all tests are automatically run on our CI in github. We will see if it fails there too :)

**Comment by k1th** [comment]
PR done and validated. Tests worked fine in CI.
