### ISSUE TITLE
ERROR [io.apiman.gateway.engine.jdbc.PollCachingJdbcRegistry]

### ISSUE THREAD

**Issue by budiholn** [apiman/apiman-docker#97]
I'm using apiman on a multi node container, but after a few days of running apiman, the following issue appears: 
ERROR [io.apiman.gateway.engine.jdbc.PollCachingJdbcRegistry] (JdbcRegistryCacheInvalidator) SQL problem encountered while running latest version query: This connection has been closed. Query: SELECT version FROM gw_dataversion Parameters: []: java.sql.SQLException: This connection has been closed. Query: SELECT version FROM gw_dataversion Parameters: []
        at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:527)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:391)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:347)
        at io.apiman.gateway.engine.jdbc.PollCachingJdbcRegistry.checkCacheVersion(PollCachingJdbcRegistry.java:199)
        at io.apiman.gateway.engine.jdbc.PollCachingJdbcRegistry$5.run(PollCachingJdbcRegistry.java:175)
        at java.lang.Thread.run(Unknown Source)

**Comment by msavy** [comment]
Please open a ticket on the main Apiman repo and fill in the full information in the "bug" ticket type.
